package Paneles;

import Dialogs.actualizarClientes;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author demo_
 */
public class PanelClientes extends javax.swing.JPanel {

    
    public PanelClientes() {
        initComponents();
        String[] encabezadosTabla = new String[]{"ID", "Nombre", "Telefono", "Correo"};
        modeloTabla.setColumnIdentifiers(encabezadosTabla);
        TablaCliente.setModel(modeloTabla);
        llenar_tabla();
    }
    DefaultTableModel modeloTabla = new DefaultTableModel();
    
    public void llenar_tabla()
    {
    String url = "jdbc:mysql://localhost:3306/ferreteria";
    String usuario = "root";
    String contraseña = "1234";

    modeloTabla.setRowCount(0);

    try {
        Connection conexion = DriverManager.getConnection(url, usuario, contraseña);
        Statement stmt = conexion.createStatement();
        conexion.createStatement();
            String consultaSQL = "SELECT id_cliente, CONCAT(nombre, ' ', primer_apellido, ' ', segundo_apellido) "
                    + "AS nombre_completo, telefono, correo FROM cliente"; 
        ResultSet rs = stmt.executeQuery(consultaSQL);

        while (rs.next()) {
            Object[] fila = {rs.getInt("id_cliente"), rs.getString("nombre_completo"),rs.getString("Telefono"),rs.getString("Correo")};
            modeloTabla.addRow(fila);
        }

        rs.close();
        stmt.close();
        conexion.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    }         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        BotonActualizarC = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Lista de clientes");

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaCliente.setSelectionBackground(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(TablaCliente);

        BotonActualizarC.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BotonActualizarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG2/update.png"))); // NOI18N
        BotonActualizarC.setText("Actualizar");
        BotonActualizarC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        BotonActualizarC.setContentAreaFilled(false);
        BotonActualizarC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(BotonActualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(207, 207, 207))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonActualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarCActionPerformed
        int filaSeleccionada = TablaCliente.getSelectedRow();

        if (filaSeleccionada != -1) {
            //Obtener ID del cliente
            int id_cliente = (int) TablaCliente.getValueAt(filaSeleccionada, 0); 
            
            //Obtener la ventana padre (JFrame) para poder abrir el JDialog
            javax.swing.JFrame framePadre = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            
            //Crear el diálogo enviando el ID para MODO EDICIÓN
            // (parent, modal=true, id_cliente)
            Dialogs.actualizarClientes ac = new Dialogs.actualizarClientes(framePadre, true, id_cliente);
            
            //Mostrarlo (el código se pausará aquí hasta que cierren la ventana)
            ac.setVisible(true);
            
            //Al volver, recargamos la tabla para ver los cambios
            llenar_tabla(); 
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un registro para actualizar.");
        }
    }//GEN-LAST:event_BotonActualizarCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarC;
    private static javax.swing.JTable TablaCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
