package Vistas;

import DAO.ClienteDAO;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuariotxt = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuariotxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        Logbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        Logbutton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Usuariotxt.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido al inicio de session");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Usuario");

        usuariotxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        passwordtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));

        Logbutton.setBackground(new java.awt.Color(255, 51, 51));
        Logbutton.setForeground(new java.awt.Color(255, 255, 255));
        Logbutton.setText("Acceder");
        Logbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogbuttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("Tipo de usuario");

        cmbTipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Empleado" }));

        Logbutton1.setBackground(new java.awt.Color(255, 51, 51));
        Logbutton1.setForeground(new java.awt.Color(255, 255, 255));
        Logbutton1.setText("Regresar");
        Logbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsuariotxtLayout = new javax.swing.GroupLayout(Usuariotxt);
        Usuariotxt.setLayout(UsuariotxtLayout);
        UsuariotxtLayout.setHorizontalGroup(
            UsuariotxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuariotxtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(UsuariotxtLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(UsuariotxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsuariotxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usuariotxt)
                        .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuariotxtLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(UsuariotxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuariotxtLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsuariotxtLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(94, 94, 94)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(UsuariotxtLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(Logbutton)
                .addGap(40, 40, 40)
                .addComponent(Logbutton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UsuariotxtLayout.setVerticalGroup(
            UsuariotxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuariotxtLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UsuariotxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UsuariotxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logbutton)
                    .addComponent(Logbutton1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(Usuariotxt, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogbuttonActionPerformed
    String usuario = usuariotxt.getText().trim();
    String password = new String(passwordtxt.getPassword());
    String tipoUsuario = (String) cmbTipoUsuario.getSelectedItem(); 

    if (usuario.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar usuario y contraseña", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        if (tipoUsuario.equals("Empleado")) {
            DAO.EmpleadoDAO empDAO = new DAO.EmpleadoDAO();
            Clases.Empleado empleadoLogueado = empDAO.validarLogin(usuario, password); 
            
            if (empleadoLogueado != null) {
                JOptionPane.showMessageDialog(this, "¡Bienvenido (Admin), " + empleadoLogueado.getNombre() + "!");
                
                Clases.Session.getInstance().login(
                        "EMPLEADO", 
                        empleadoLogueado.getIdEmpleado(), 
                        empleadoLogueado.getNombre()
                );
                
                inicio in = new inicio(); 
               
                in.setLocationRelativeTo(null);
                this.dispose();
                in.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña de Empleado incorrectos", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
            }

        } else if (tipoUsuario.equals("Cliente")) {
            DAO.ClienteDAO cliDAO = new DAO.ClienteDAO();
            Clases.Cliente clienteLogueado = cliDAO.login(usuario, password);

            if (clienteLogueado != null) {
                JOptionPane.showMessageDialog(this, "¡Bienvenido (Cliente), " + clienteLogueado.getNombre() + "!");
                
                Clases.Session.getInstance().login(
                        "CLIENTE", 
                        clienteLogueado.getIdCliente(), 
                        clienteLogueado.getNombre()
                );
                
                inicio in = new inicio();
                
                in.setLocationRelativeTo(null);
                this.dispose();
                in.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña de Cliente incorrectos", "Acceso denegado", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error en la conexión a la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_LogbuttonActionPerformed

    private void Logbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logbutton1ActionPerformed
        this.dispose();
            index inicio = new index();
            inicio.setLocationRelativeTo(this);
            inicio.setVisible(true);
    }//GEN-LAST:event_Logbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logbutton;
    private javax.swing.JButton Logbutton1;
    private javax.swing.JPanel Usuariotxt;
    private javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField usuariotxt;
    // End of variables declaration//GEN-END:variables
}
